type Mutation {
  addFood(food: String!): [String]
  addEaten(eaten: String!): [String]
  removeEaten(eaten: String!): [String]
  randomFood(id: String): Food
  say(msg: String!): Boolean
}

type Query {
  gql: String
  foods: [String]
  eaten: [String]
  cryptoPrice(id: String!): Float
}

type Food {
  food: String
  id: String
  price: Float
}
